name: publish

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: dockerhub.io
  IMAGE_NAME: dallotech/nextjs-blog:latest

jobs:
    publish:
        name: publish image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Login docker
          run: |
            echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
        - name: Build and Publish
          run: |
            docker-compose build
            docker-compose push


    deploy:
        needs: publish
        name: deploy image
        runs-on: ubuntu-latest

        steps:
        - name: connect and pull
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: ${{secrets.REMOTE_SSH_HOST}}
            username: ${{secrets.REMOTE_SSH_USER}}
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: |
              cd ${{ secrets.REMOTE_WORK_DIR }}
              docker-compose pull
              docker-compose up
